<a href="https://colab.research.google.com/github/anucodes-hub/Machine-Learning/blob/main/ml_program1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Machine Learning Program-1

Name: Anushka Kar

UEC2024106

Date: 22-01-2026

Title: Download and Access data files in python

In [ ]:
import pandas as pd

In [ ]:
myfile_1=pd.read_csv('myfile_2024_25.csv')

In [ ]:
print(myfile_1)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0
457                NaN        NaN

[458 rows x 9 columns]

In [ ]:
display(myfile_1)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Reading and unzipping the file

In [ ]:
! unzip "archive_2024_25"

Archive:  archive_2024_25.zip
replace WorldCupMatches.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: WorldCupMatches.csv
replace WorldCupPlayers.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace WorldCups.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n

In [ ]:
myfile_2=pd.read_csv('WorldCups.csv')

In [ ]:
print(myfile_2)

    Year       Country      Winner      Runners-Up        Third  \
0   1930       Uruguay     Uruguay       Argentina          USA
1   1934         Italy       Italy  Czechoslovakia      Germany
2   1938        France       Italy         Hungary       Brazil
3   1950        Brazil     Uruguay          Brazil       Sweden
4   1954   Switzerland  Germany FR         Hungary      Austria
5   1958        Sweden      Brazil          Sweden       France
6   1962         Chile      Brazil  Czechoslovakia        Chile
7   1966       England     England      Germany FR     Portugal
8   1970        Mexico      Brazil           Italy   Germany FR
9   1974       Germany  Germany FR     Netherlands       Poland
10  1978     Argentina   Argentina     Netherlands       Brazil
11  1982         Spain       Italy      Germany FR       Poland
12  1986        Mexico   Argentina      Germany FR       France
13  1990         Italy  Germany FR       Argentina        Italy
14  1994           USA      Brazil           Italy       Sweden
15  1998        France      France          Brazil      Croatia
16  2002   Korea/Japan      Brazil         Germany       Turkey
17  2006       Germany       Italy          France      Germany
18  2010  South Africa       Spain     Netherlands      Germany
19  2014        Brazil     Germany       Argentina  Netherlands

            Fourth  GoalsScored  QualifiedTeams  MatchesPlayed Attendance
0       Yugoslavia           70              13             18    590.549
1          Austria           70              16             17    363.000
2           Sweden           84              15             18    375.700
3            Spain           88              13             22  1.045.246
4          Uruguay          140              16             26    768.607
5       Germany FR          126              16             35    819.810
6       Yugoslavia           89              16             32    893.172
7     Soviet Union           89              16             32  1.563.135
8          Uruguay           95              16             32  1.603.975
9           Brazil           97              16             38  1.865.753
10           Italy          102              16             38  1.545.791
11          France          146              24             52  2.109.723
12         Belgium          132              24             52  2.394.031
13         England          115              24             52  2.516.215
14        Bulgaria          141              24             52  3.587.538
15     Netherlands          171              32             64  2.785.100
16  Korea Republic          161              32             64  2.705.197
17        Portugal          147              32             64  3.359.439
18         Uruguay          145              32             64  3.178.856
19          Brazil          171              32             64  3.386.810

Read and Display after mounting Drive

In [ ]:
my_file3=pd.read_csv('/content/drive/MyDrive/ML_programs/myfile_2024_25.csv')

In [ ]:
display(my_file3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
! unzip "/content/drive/MyDrive/ML_programs/archive_2024_25.zip"

Archive:  /content/drive/MyDrive/ML_programs/archive_2024_25.zip
  inflating: WorldCupMatches.csv
  inflating: WorldCupPlayers.csv
  inflating: WorldCups.csv

In [ ]:
my_file4=pd.read_csv("WorldCupPlayers.csv")

In [ ]:
display(my_file4)

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,NaN
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,NaN
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40'
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70'
4,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,NaN
...,...,...,...,...,...,...,...,...,...
37779,255959,300186501,ARG,SABELLA Alejandro (ARG),N,19,ALVAREZ,NaN,NaN
37780,255959,300186501,GER,LOEW Joachim (GER),N,6,KHEDIRA,NaN,NaN
37781,255959,300186501,ARG,SABELLA Alejandro (ARG),N,20,AGUERO,NaN,IH46' Y65'
37782,255959,300186501,GER,LOEW Joachim (GER),N,21,MUSTAFI,NaN,NaN
37783,255959,300186501,ARG,SABELLA Alejandro (ARG),N,23,BASANTA,NaN,NaN

Importing dataset from kaggle

In [ ]:
my_file5= pd.read_csv("/1- mental-illnesses-prevalence.csv")

In [ ]:
display(my_file5)

,Entity,Code,Year,Schizophrenia disorders (share of population) - Sex: Both - Age: Age-standardized,Depressive disorders (share of population) - Sex: Both - Age: Age-standardized,Anxiety disorders (share of population) - Sex: Both - Age: Age-standardized,Bipolar disorders (share of population) - Sex: Both - Age: Age-standardized,Eating disorders (share of population) - Sex: Both - Age: Age-standardized
0,Afghanistan,AFG,1990,0.223206,4.996118,4.713314,0.703023,0.127700
1,Afghanistan,AFG,1991,0.222454,4.989290,4.702100,0.702069,0.123256
2,Afghanistan,AFG,1992,0.221751,4.981346,4.683743,0.700792,0.118844
3,Afghanistan,AFG,1993,0.220987,4.976958,4.673549,0.700087,0.115089
4,Afghanistan,AFG,1994,0.220183,4.977782,4.670810,0.699898,0.111815
...,...,...,...,...,...,...,...,...
6415,Zimbabwe,ZWE,2015,0.201042,3.407624,3.184012,0.538596,0.095652
6416,Zimbabwe,ZWE,2016,0.201319,3.410755,3.187148,0.538593,0.096662
6417,Zimbabwe,ZWE,2017,0.201639,3.411965,3.188418,0.538589,0.097330
6418,Zimbabwe,ZWE,2018,0.201976,3.406929,3.172111,0.538585,0.097909
6419,Zimbabwe,ZWE,2019,0.202482,3.395476,3.137017,0.538580,0.098295